name: PR Test
on: [pull_request]
jobs:
  test-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install Node v20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Clean install deps
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn run test
